CREATE TABLE `feasibilityStudies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectName` varchar(500) NOT NULL,
	`community` varchar(255),
	`plotNumber` varchar(100),
	`projectDescription` varchar(255),
	`landUse` varchar(255),
	`plotArea` int,
	`plotAreaM2` int,
	`gfaResidential` int,
	`gfaRetail` int,
	`gfaOffices` int,
	`totalGfa` int,
	`saleableResidentialPct` int DEFAULT 90,
	`saleableRetailPct` int DEFAULT 99,
	`saleableOfficesPct` int DEFAULT 90,
	`estimatedBua` int,
	`numberOfUnits` int,
	`landPrice` int,
	`agentCommissionLandPct` int DEFAULT 1,
	`soilInvestigation` int,
	`topographySurvey` int,
	`authoritiesFee` int,
	`constructionCostPerSqft` int,
	`communityFee` int,
	`designFeePct` int DEFAULT 2,
	`supervisionFeePct` int DEFAULT 2,
	`separationFeePerM2` int DEFAULT 40,
	`contingenciesPct` int DEFAULT 2,
	`developerFeePct` int DEFAULT 5,
	`agentCommissionSalePct` int DEFAULT 5,
	`marketingPct` int DEFAULT 2,
	`reraOffplanFee` int DEFAULT 150000,
	`reraUnitFee` int DEFAULT 850,
	`nocFee` int DEFAULT 10000,
	`escrowFee` int DEFAULT 140000,
	`bankCharges` int DEFAULT 20000,
	`surveyorFees` int DEFAULT 12000,
	`reraAuditFees` int DEFAULT 18000,
	`reraInspectionFees` int DEFAULT 70000,
	`residentialSalePrice` int,
	`retailSalePrice` int,
	`officesSalePrice` int,
	`comoProfitSharePct` int DEFAULT 15,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `feasibilityStudies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `feasibilityStudies` ADD CONSTRAINT `feasibilityStudies_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;