ALTER TABLE `projects` ADD `titleDeedNumber` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `ddaNumber` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `masterDevRef` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `plotAreaSqm` decimal(12,2);--> statement-breakpoint
ALTER TABLE `projects` ADD `plotAreaSqft` decimal(12,2);--> statement-breakpoint
ALTER TABLE `projects` ADD `gfaSqm` decimal(12,2);--> statement-breakpoint
ALTER TABLE `projects` ADD `gfaSqft` decimal(12,2);--> statement-breakpoint
ALTER TABLE `projects` ADD `permittedUse` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `ownershipType` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `subdivisionRestrictions` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `masterDevName` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `masterDevAddress` varchar(500);--> statement-breakpoint
ALTER TABLE `projects` ADD `sellerName` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `sellerAddress` varchar(500);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerName` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerNationality` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerPassport` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerAddress` varchar(500);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerPhone` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `buyerEmail` varchar(320);--> statement-breakpoint
ALTER TABLE `projects` ADD `electricityAllocation` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `waterAllocation` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `sewageAllocation` varchar(100);--> statement-breakpoint
ALTER TABLE `projects` ADD `tripAM` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `tripLT` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `tripPM` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `effectiveDate` varchar(50);--> statement-breakpoint
ALTER TABLE `projects` ADD `constructionPeriod` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `constructionStartDate` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `completionDate` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `constructionConditions` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `saleRestrictions` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `resaleConditions` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `communityCharges` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `registrationAuthority` varchar(255);--> statement-breakpoint
ALTER TABLE `projects` ADD `adminFee` int;--> statement-breakpoint
ALTER TABLE `projects` ADD `clearanceFee` int;--> statement-breakpoint
ALTER TABLE `projects` ADD `compensationAmount` int;--> statement-breakpoint
ALTER TABLE `projects` ADD `governingLaw` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `disputeResolution` text;