CREATE TABLE `agentActivityLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentName` varchar(50) NOT NULL,
	`agentModel` varchar(50),
	`actionType` enum('tool_call','chat_response','file_read','file_write','db_read','db_write','email_action','drive_action','agent_comm','task_execution','meeting_action','analysis','error') NOT NULL,
	`toolName` varchar(100),
	`inputSummary` text,
	`outputSummary` text,
	`fullInput` mediumtext,
	`fullOutput` mediumtext,
	`activityStatus` enum('success','failure','partial','pending') NOT NULL,
	`errorMessage` text,
	`errorDetails` text,
	`triggerSource` varchar(100),
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`userId` int,
	`durationMs` int,
	`tokensUsed` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agentActivityLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documentIndex` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sourceType` enum('google_drive','email_attachment','upload','agent_output') NOT NULL,
	`sourceId` varchar(255),
	`sourcePath` varchar(1000),
	`sourceName` varchar(500) NOT NULL,
	`fileType` enum('pdf','excel','word','image','text','google_doc','google_sheet','google_slides','csv','other') NOT NULL,
	`mimeType` varchar(255),
	`fileSizeBytes` int,
	`extractedText` longtext,
	`extractedTextLength` int,
	`structuredData` longtext,
	`summary` text,
	`category` varchar(100),
	`projectId` int,
	`consultantId` int,
	`tags` text,
	`language` varchar(10),
	`indexStatus` enum('pending','processing','indexed','failed','needs_update') NOT NULL DEFAULT 'pending',
	`indexError` text,
	`indexedBy` varchar(50),
	`searchVector` text,
	`lastAccessedAt` timestamp,
	`accessCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documentIndex_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `specialistKnowledge` (
	`id` int AUTO_INCREMENT NOT NULL,
	`knowledgeDomain` enum('rera_law','dubai_municipality','building_codes','market_prices','como_context','como_people','como_preferences','como_workflow','consultant_info','project_standards','general') NOT NULL,
	`category` varchar(100) NOT NULL,
	`title` varchar(500) NOT NULL,
	`content` longtext NOT NULL,
	`keywords` text,
	`source` varchar(255),
	`sourceUrl` varchar(1000),
	`isActive` int NOT NULL DEFAULT 1,
	`validFrom` timestamp,
	`validUntil` timestamp,
	`addedBy` varchar(50),
	`lastUsedAt` timestamp,
	`useCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `specialistKnowledge_id` PRIMARY KEY(`id`)
);
