CREATE TABLE `competition_pricing` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectId` int NOT NULL,
	`aiSmartReport` text,
	`aiRecommendationsJson` text,
	`aiReportGeneratedAt` timestamp,
	`optStudioPrice` int DEFAULT 0,
	`opt1brPrice` int DEFAULT 0,
	`opt2brPrice` int DEFAULT 0,
	`opt3brPrice` int DEFAULT 0,
	`optRetailSmallPrice` int DEFAULT 0,
	`optRetailMediumPrice` int DEFAULT 0,
	`optRetailLargePrice` int DEFAULT 0,
	`optOfficeSmallPrice` int DEFAULT 0,
	`optOfficeMediumPrice` int DEFAULT 0,
	`optOfficeLargePrice` int DEFAULT 0,
	`baseStudioPrice` int DEFAULT 0,
	`base1brPrice` int DEFAULT 0,
	`base2brPrice` int DEFAULT 0,
	`base3brPrice` int DEFAULT 0,
	`baseRetailSmallPrice` int DEFAULT 0,
	`baseRetailMediumPrice` int DEFAULT 0,
	`baseRetailLargePrice` int DEFAULT 0,
	`baseOfficeSmallPrice` int DEFAULT 0,
	`baseOfficeMediumPrice` int DEFAULT 0,
	`baseOfficeLargePrice` int DEFAULT 0,
	`consStudioPrice` int DEFAULT 0,
	`cons1brPrice` int DEFAULT 0,
	`cons2brPrice` int DEFAULT 0,
	`cons3brPrice` int DEFAULT 0,
	`consRetailSmallPrice` int DEFAULT 0,
	`consRetailMediumPrice` int DEFAULT 0,
	`consRetailLargePrice` int DEFAULT 0,
	`consOfficeSmallPrice` int DEFAULT 0,
	`consOfficeMediumPrice` int DEFAULT 0,
	`consOfficeLargePrice` int DEFAULT 0,
	`paymentBookingPct` decimal(5,2) DEFAULT '10',
	`paymentBookingTiming` varchar(255) DEFAULT 'عند التوقيع',
	`paymentConstructionPct` decimal(5,2) DEFAULT '60',
	`paymentConstructionTiming` varchar(255) DEFAULT 'أثناء الإنشاء',
	`paymentHandoverPct` decimal(5,2) DEFAULT '30',
	`paymentHandoverTiming` varchar(255) DEFAULT 'عند التسليم',
	`paymentDeferredPct` decimal(5,2) DEFAULT '0',
	`paymentDeferredTiming` varchar(255),
	`activeScenario` varchar(20) DEFAULT 'base',
	`isApproved` int NOT NULL DEFAULT 0,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competition_pricing_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `competition_pricing` ADD CONSTRAINT `competition_pricing_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `competition_pricing` ADD CONSTRAINT `competition_pricing_projectId_projects_id_fk` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE no action ON UPDATE no action;