CREATE TABLE `costs_cash_flow` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`landPrice` int DEFAULT 0,
	`agentCommissionLandPct` decimal(5,2) DEFAULT '1',
	`landRegistrationPct` decimal(5,2) DEFAULT '4',
	`soilInvestigation` int DEFAULT 0,
	`topographySurvey` int DEFAULT 0,
	`designFeePct` decimal(5,2) DEFAULT '2',
	`supervisionFeePct` decimal(5,2) DEFAULT '2',
	`authoritiesFee` int DEFAULT 0,
	`separationFeePerM2` int DEFAULT 40,
	`constructionCostPerSqft` int DEFAULT 0,
	`communityFee` int DEFAULT 0,
	`contingenciesPct` decimal(5,2) DEFAULT '2',
	`developerFeePct` decimal(5,2) DEFAULT '5',
	`agentCommissionSalePct` decimal(5,2) DEFAULT '5',
	`marketingPct` decimal(5,2) DEFAULT '2',
	`reraOffplanFee` int DEFAULT 150000,
	`reraUnitFee` int DEFAULT 850,
	`nocFee` int DEFAULT 10000,
	`escrowFee` int DEFAULT 140000,
	`bankCharges` int DEFAULT 20000,
	`surveyorFees` int DEFAULT 12000,
	`reraAuditFees` int DEFAULT 18000,
	`reraInspectionFees` int DEFAULT 70000,
	`comoProfitSharePct` decimal(5,2) DEFAULT '15',
	`projectDurationMonths` int DEFAULT 36,
	`constructionStartMonth` int DEFAULT 6,
	`constructionDurationMonths` int DEFAULT 24,
	`salesStartMonth` int DEFAULT 1,
	`salesDurationMonths` int DEFAULT 30,
	`salesPhase1Pct` decimal(5,2) DEFAULT '30',
	`salesPhase2Pct` decimal(5,2) DEFAULT '40',
	`salesPhase3Pct` decimal(5,2) DEFAULT '30',
	`aiSmartReport` text,
	`aiRecommendationsJson` text,
	`isApproved` int NOT NULL DEFAULT 0,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `costs_cash_flow_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `costs_cash_flow` ADD CONSTRAINT `costs_cash_flow_projectId_projects_id_fk` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `costs_cash_flow` ADD CONSTRAINT `costs_cash_flow_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;