ALTER TABLE `projects`
  ADD COLUMN `villaCount` INT NOT NULL DEFAULT 0,
  ADD COLUMN `townhouseCount` INT NOT NULL DEFAULT 0,
  ADD COLUMN `villaArea` INT NOT NULL DEFAULT 0,
  ADD COLUMN `townhouseArea` INT NOT NULL DEFAULT 0,
  ADD COLUMN `villaPrice` INT NOT NULL DEFAULT 0,
  ADD COLUMN `townhousePrice` INT NOT NULL DEFAULT 0;
