CREATE TABLE `business_partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_name` varchar(255) NOT NULL,
	`category` varchar(100),
	`contact_person` varchar(255),
	`mobile_number` varchar(50),
	`email_address` varchar(255),
	`website` varchar(255),
	`status` enum('quoted_only','under_review','appointed','not_selected') NOT NULL DEFAULT 'quoted_only',
	`notes` text,
	`commercial_license_url` text,
	`commercial_license_name` varchar(255),
	`vat_certificate_url` text,
	`vat_certificate_name` varchar(255),
	`authorized_signatory_doc_url` text,
	`authorized_signatory_doc_name` varchar(255),
	`other_documents_json` text,
	`beneficiary_name` varchar(255),
	`account_number` varchar(100),
	`iban` varchar(100),
	`bank_name` varchar(255),
	`branch_name` varchar(255),
	`currency` varchar(10) DEFAULT 'AED',
	`bank_notes` text,
	`signatory_name` varchar(255),
	`signatory_title` varchar(255),
	`signatory_email` varchar(255),
	`signatory_phone` varchar(50),
	`signatory_image_url` text,
	`created_at` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE `payment_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_number` varchar(50) NOT NULL,
	`partner_id` int NOT NULL,
	`project_name` varchar(255),
	`description` text NOT NULL,
	`amount` decimal(15,2) NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'AED',
	`approved_quote_url` text,
	`approved_quote_name` varchar(255),
	`status` enum('new','pending_wael','pending_sheikh','approved','rejected','needs_revision') NOT NULL DEFAULT 'new',
	`wael_reviewed_at` timestamp,
	`wael_decision` enum('approved','rejected','needs_revision'),
	`wael_notes` text,
	`sheikh_reviewed_at` timestamp,
	`sheikh_decision` enum('approved','rejected'),
	`sheikh_notes` text,
	`finance_email_sent_at` timestamp,
	`stamped_quote_url` text,
	`submitted_by` int,
	`created_at` timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE `payment_requests` ADD CONSTRAINT `payment_requests_partner_id_business_partners_id_fk` FOREIGN KEY (`partner_id`) REFERENCES `business_partners`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `payment_requests` ADD CONSTRAINT `payment_requests_submitted_by_users_id_fk` FOREIGN KEY (`submitted_by`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;