-- Project-by-project DESIGN_SCOPE_ENCYCLOPEDIA_V1 selections.
-- Majan mixed-use was reviewed and approved item-by-item by the owner.
-- The other five projects are editable 95% working drafts based on their
-- recorded use, size, and known project characteristics. No supervision,
-- consultant offer, fee, evaluation result, or financial table is updated.

UPDATE project_consultant_requirements requirement
JOIN project_consultant_requirement_sets requirement_set
  ON requirement_set.id = requirement.requirement_set_id
JOIN cpa_projects project
  ON project.project_id = requirement_set.project_id
SET requirement.is_required = CASE
  WHEN project.plot_number = '6457879' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI',
    'AV_DESIGN','CCTV_SECURITY_DESIGN','SIRA_SUBMISSION','ACCESS_INTERCOM','GREEN_BUILDING',
    'CFD_MODELLING','ACOUSTIC_VIBRATION','VERTICAL_TRANSPORT','WASTE_MANAGEMENT',
    'FACADE_ENGINEERING','FACADE_LIGHTING','INTERIOR_LIGHTING','FACADE_ACCESS_BMU',
    'WIND_TUNNEL','ID_PUBLIC_AREAS','LANDSCAPE_DESIGN','IRRIGATION_DESIGN','WATER_FEATURES',
    'WAYFINDING_SIGNAGE','PARKING_STRATEGY','TIS'
  ) THEN 1
  WHEN project.plot_number = '6457956' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI',
    'AV_DESIGN','CCTV_SECURITY_DESIGN','SIRA_SUBMISSION','ACCESS_INTERCOM','GREEN_BUILDING',
    'CFD_MODELLING','ACOUSTIC_VIBRATION','VERTICAL_TRANSPORT','WASTE_MANAGEMENT',
    'FACADE_ENGINEERING','FACADE_LIGHTING','INTERIOR_LIGHTING','FACADE_ACCESS_BMU',
    'ID_PUBLIC_AREAS','LANDSCAPE_DESIGN','IRRIGATION_DESIGN','WATER_FEATURES',
    'WAYFINDING_SIGNAGE','PARKING_STRATEGY','TIS','RETAIL_PLANNING',
    'TENANT_HANDBOOK_DESIGN','TENANT_HANDBOOK_TECH','LOOSE_FURNITURE_FFE'
  ) THEN 1
  WHEN project.plot_number = '3260885' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI',
    'CCTV_SECURITY_DESIGN','SIRA_SUBMISSION','ACCESS_INTERCOM','GREEN_BUILDING','CFD_MODELLING',
    'ACOUSTIC_VIBRATION','VERTICAL_TRANSPORT','WASTE_MANAGEMENT','FACADE_ENGINEERING',
    'FACADE_LIGHTING','INTERIOR_LIGHTING','ID_PUBLIC_AREAS','ID_UNIT_PROTOTYPES',
    'LANDSCAPE_DESIGN','IRRIGATION_DESIGN','WATER_FEATURES','WAYFINDING_SIGNAGE',
    'PARKING_STRATEGY','TIS'
  ) THEN 1
  WHEN project.plot_number = '6185392' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI','AV_DESIGN',
    'CCTV_SECURITY_DESIGN','SIRA_SUBMISSION','ACCESS_INTERCOM','GREEN_BUILDING','CFD_MODELLING',
    'ACOUSTIC_VIBRATION','VERTICAL_TRANSPORT','WASTE_MANAGEMENT','FACADE_ENGINEERING',
    'FACADE_LIGHTING','INTERIOR_LIGHTING','ID_PUBLIC_AREAS','ID_UNIT_PROTOTYPES',
    'LANDSCAPE_DESIGN','IRRIGATION_DESIGN','WATER_FEATURES','WAYFINDING_SIGNAGE',
    'PARKING_STRATEGY','TIS','RETAIL_PLANNING','TENANT_HANDBOOK_DESIGN','TENANT_HANDBOOK_TECH'
  ) THEN 1
  WHEN project.plot_number = '6182776' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI',
    'CCTV_SECURITY_DESIGN','SIRA_SUBMISSION','ACCESS_INTERCOM','GREEN_BUILDING','CFD_MODELLING',
    'ACOUSTIC_VIBRATION','VERTICAL_TRANSPORT','WASTE_MANAGEMENT','FACADE_ENGINEERING',
    'FACADE_LIGHTING','INTERIOR_LIGHTING','ID_PUBLIC_AREAS','ID_UNIT_PROTOTYPES',
    'LANDSCAPE_DESIGN','IRRIGATION_DESIGN','WATER_FEATURES','WAYFINDING_SIGNAGE',
    'PARKING_STRATEGY','TIS'
  ) THEN 1
  WHEN project.plot_number = '6180578' AND requirement.code IN (
    'LEAD_AOR','ARCH_DESIGN','STRUCTURAL_DESIGN','MEP_ENGINEERING','INFRASTRUCTURE','FLS',
    'BIM_MANAGEMENT','AUTHORITY_SUBMISSIONS','BUILDING_PERMIT','TENDER_SERVICES',
    'IFC_CONTRACT_DOCS','QS_BOQ_SPECS','ELV_COORDINATION','TELECOM','ICT_DATA_WIFI',
    'CCTV_SECURITY_DESIGN','ACCESS_INTERCOM','GREEN_BUILDING','WASTE_MANAGEMENT',
    'FACADE_LIGHTING','INTERIOR_LIGHTING','ID_UNIT_PROTOTYPES','LANDSCAPE_DESIGN',
    'IRRIGATION_DESIGN','WATER_FEATURES','WAYFINDING_SIGNAGE'
  ) THEN 1
  ELSE 0
END
WHERE requirement_set.status = 'DRAFT'
  AND requirement_set.notes LIKE 'DESIGN_SCOPE_ENCYCLOPEDIA_V1%'
  AND requirement.workstream = 'DESIGN'
  AND project.plot_number IN ('6457879','6457956','3260885','6185392','6182776','6180578');

UPDATE project_consultant_requirement_sets requirement_set
JOIN cpa_projects project ON project.project_id = requirement_set.project_id
SET requirement_set.notes = CASE project.plot_number
      WHEN '6457879' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | OWNER_APPROVED_MAJAN_SCOPE_V1 | 36 بندًا مختارًا | CFD وWind Tunnel عند الحاجة | Specialist Interior Lighting للمناطق العامة والتجارية فقط | رسوم SIRA الحكومية على المالك'
      WHEN '6457956' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | ASSISTED_SCOPE_DRAFT_V1 | مركز تجاري G+4 بمساحة 900,000 قدم² | 39 بندًا مختارًا | قابل لتعديل المالك'
      WHEN '3260885' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | ASSISTED_SCOPE_DRAFT_V1 | مبنى سكني G+7 بمساحة 110,000 قدم² | 34 بندًا مختارًا | قابل لتعديل المالك'
      WHEN '6185392' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | ASSISTED_SCOPE_DRAFT_V1 | مشروع متعدد الاستخدامات بمساحة 114,284 قدم² | 38 بندًا مختارًا | قابل لتعديل المالك'
      WHEN '6182776' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | ASSISTED_SCOPE_DRAFT_V1 | مشروع سكني بمساحة 205,000 قدم² | 34 بندًا مختارًا | قابل لتعديل المالك'
      WHEN '6180578' THEN 'DESIGN_SCOPE_ENCYCLOPEDIA_V1 | 43 بند تصميم فقط | ASSISTED_SCOPE_DRAFT_V1 | مشروع فلل بمساحة 25,000 قدم² | 26 بندًا مختارًا | قابل لتعديل المالك'
      ELSE requirement_set.notes
    END
WHERE requirement_set.status = 'DRAFT'
  AND requirement_set.notes LIKE 'DESIGN_SCOPE_ENCYCLOPEDIA_V1%'
  AND project.plot_number IN ('6457879','6457956','3260885','6185392','6182776','6180578');

UPDATE project_consultant_requirement_sets requirement_set
JOIN cpa_projects project ON project.project_id = requirement_set.project_id
SET requirement_set.status = 'APPROVED',
    requirement_set.approved_at = CURRENT_TIMESTAMP
WHERE requirement_set.status = 'DRAFT'
  AND requirement_set.notes LIKE '%OWNER_APPROVED_MAJAN_SCOPE_V1%'
  AND project.plot_number = '6457879';
