-- COMO Next executive-office foundation
-- Additive only: no existing table is altered and no existing row is updated.

CREATE TABLE `como_next_project_access` (
  `id` int AUTO_INCREMENT NOT NULL,
  `project_id` int NOT NULL,
  `user_id` int NOT NULL,
  `access_role` enum('manager','contributor','viewer') NOT NULL DEFAULT 'viewer',
  `granted_by_user_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_project_access_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_access_project_user_uq` UNIQUE (`project_id`,`user_id`),
  KEY `como_next_access_user_role_idx` (`user_id`,`access_role`),
  CONSTRAINT `como_next_access_project_fk` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_access_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_access_granted_by_fk` FOREIGN KEY (`granted_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
);

CREATE TABLE `como_next_parties` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `party_type` enum('organization','person','authority') NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `legal_name` varchar(500),
  `jurisdiction` varchar(120),
  `registration_number` varchar(120),
  `party_status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(64),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_parties_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_party_legal_identity_uq` UNIQUE (`user_id`,`jurisdiction`,`registration_number`),
  KEY `como_next_party_name_idx` (`user_id`,`display_name`),
  KEY `como_next_party_source_idx` (`source_system`,`source_record_id`),
  CONSTRAINT `como_next_party_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
);

CREATE TABLE `como_next_project_parties` (
  `id` int AUTO_INCREMENT NOT NULL,
  `project_id` int NOT NULL,
  `party_id` int NOT NULL,
  `role_code` varchar(80) NOT NULL,
  `relationship_status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_project_parties_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_project_party_role_uq` UNIQUE (`project_id`,`party_id`,`role_code`),
  CONSTRAINT `como_next_project_party_project_id_uq` UNIQUE (`project_id`,`id`),
  KEY `como_next_project_party_state_idx` (`project_id`,`relationship_status`,`role_code`),
  KEY `como_next_project_party_lookup_idx` (`party_id`,`relationship_status`),
  CONSTRAINT `como_next_project_party_project_fk` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_project_party_party_fk` FOREIGN KEY (`party_id`) REFERENCES `como_next_parties` (`id`) ON DELETE RESTRICT
);

CREATE TABLE `como_next_work_files` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `project_id` int NOT NULL,
  `title` varchar(500) NOT NULL,
  `governing_question` text NOT NULL,
  `desired_outcome` text NOT NULL,
  `work_file_status` enum('draft','open','waiting','blocked','ready_to_close','closed','cancelled') NOT NULL DEFAULT 'open',
  `priority` enum('normal','important','urgent') NOT NULL DEFAULT 'normal',
  `owner_user_id` int NOT NULL,
  `closure_evidence_ref` text,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(64),
  `opened_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_work_files_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_work_file_project_id_uq` UNIQUE (`project_id`,`id`),
  CONSTRAINT `como_next_work_file_source_uq` UNIQUE (`source_system`,`source_record_id`),
  KEY `como_next_work_file_project_state_idx` (`project_id`,`work_file_status`,`updated_at`),
  KEY `como_next_work_file_owner_state_idx` (`owner_user_id`,`work_file_status`,`updated_at`),
  CONSTRAINT `como_next_work_file_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_work_file_project_fk` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_work_file_owner_fk` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_work_file_closed_evidence_ck` CHECK (`work_file_status` <> 'closed' OR `closure_evidence_ref` IS NOT NULL)
);

CREATE TABLE `como_next_work_file_parties` (
  `id` int AUTO_INCREMENT NOT NULL,
  `project_id` int NOT NULL,
  `work_file_id` int NOT NULL,
  `project_party_id` int NOT NULL,
  `relationship_role` varchar(80) NOT NULL DEFAULT 'counterparty',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_work_file_parties_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_work_file_party_uq` UNIQUE (`work_file_id`,`project_party_id`),
  CONSTRAINT `como_next_work_file_party_file_fk` FOREIGN KEY (`project_id`,`work_file_id`) REFERENCES `como_next_work_files` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_work_file_party_project_party_fk` FOREIGN KEY (`project_id`,`project_party_id`) REFERENCES `como_next_project_parties` (`project_id`,`id`) ON DELETE RESTRICT
);

CREATE TABLE `como_next_actions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `project_id` int NOT NULL,
  `work_file_id` int NOT NULL,
  `title` varchar(500) NOT NULL,
  `description` text,
  `acceptance_criteria` text NOT NULL,
  `owner_type` enum('human','manus','team') NOT NULL DEFAULT 'human',
  `owner_user_id` int,
  `waiting_project_party_id` int,
  `action_status` enum('open','in_progress','waiting_external','completed_pending_verification','verified','cancelled') NOT NULL DEFAULT 'open',
  `priority` enum('normal','important','urgent') NOT NULL DEFAULT 'normal',
  `due_at` timestamp NULL,
  `follow_up_at` timestamp NULL,
  `attention_at` timestamp NULL,
  `evidence_reference` text,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(64),
  `completed_at` timestamp NULL,
  `verified_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_actions_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_action_project_id_uq` UNIQUE (`project_id`,`id`),
  CONSTRAINT `como_next_action_source_uq` UNIQUE (`source_system`,`source_record_id`),
  KEY `como_next_action_owner_attention_idx` (`owner_type`,`owner_user_id`,`action_status`,`attention_at`),
  KEY `como_next_action_project_attention_idx` (`project_id`,`action_status`,`attention_at`),
  KEY `como_next_action_file_attention_idx` (`work_file_id`,`action_status`,`attention_at`),
  CONSTRAINT `como_next_action_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_action_owner_fk` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_action_work_file_fk` FOREIGN KEY (`project_id`,`work_file_id`) REFERENCES `como_next_work_files` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_action_waiting_party_fk` FOREIGN KEY (`project_id`,`waiting_project_party_id`) REFERENCES `como_next_project_parties` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_action_human_owner_ck` CHECK (`owner_type` <> 'human' OR `owner_user_id` IS NOT NULL),
  CONSTRAINT `como_next_action_waiting_party_ck` CHECK (`action_status` <> 'waiting_external' OR `waiting_project_party_id` IS NOT NULL),
  CONSTRAINT `como_next_action_verified_evidence_ck` CHECK (`action_status` <> 'verified' OR `evidence_reference` IS NOT NULL),
  CONSTRAINT `como_next_action_attention_ck` CHECK (`attention_at` <=> COALESCE(`follow_up_at`,`due_at`))
);

CREATE TABLE `como_next_work_file_events` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `user_id` int NOT NULL,
  `project_id` int NOT NULL,
  `work_file_id` int NOT NULL,
  `action_id` int,
  `sequence_no` int NOT NULL,
  `actor_type` enum('human','manus','system') NOT NULL DEFAULT 'human',
  `actor_user_id` int,
  `event_type` varchar(80) NOT NULL,
  `summary` varchar(1000) NOT NULL,
  `payload_json` text,
  `idempotency_key` varchar(128),
  `occurred_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_work_file_events_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_event_sequence_uq` UNIQUE (`work_file_id`,`sequence_no`),
  CONSTRAINT `como_next_event_idempotency_uq` UNIQUE (`idempotency_key`),
  KEY `como_next_event_project_time_idx` (`project_id`,`occurred_at`),
  KEY `como_next_event_action_time_idx` (`action_id`,`occurred_at`),
  CONSTRAINT `como_next_event_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_event_actor_fk` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_event_work_file_fk` FOREIGN KEY (`project_id`,`work_file_id`) REFERENCES `como_next_work_files` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_event_action_fk` FOREIGN KEY (`project_id`,`action_id`) REFERENCES `como_next_actions` (`project_id`,`id`) ON DELETE RESTRICT
);
