-- COMO Next operational promotion tables
-- Additive only. No legacy or financial table is modified.

CREATE TABLE `como_next_party_contacts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `party_id` int NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `email` varchar(320),
  `phone` varchar(120),
  `job_title` varchar(255),
  `is_primary` tinyint NOT NULL DEFAULT 0,
  `notes` text,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_party_contacts_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_party_contact_party_fk` FOREIGN KEY (`party_id`) REFERENCES `como_next_parties` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_party_contact_source_uq` UNIQUE (`source_system`, `source_record_id`),
  INDEX `como_next_party_contact_party_idx` (`party_id`, `is_primary`),
  INDEX `como_next_party_contact_email_idx` (`email`)
);

CREATE TABLE `como_next_work_memory` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `project_id` int NOT NULL,
  `work_file_id` int NOT NULL,
  `memory_type` enum('material','work_product','decision','note') NOT NULL,
  `entry_type` varchar(120),
  `title` varchar(1000) NOT NULL,
  `body` longtext,
  `source_status` varchar(80),
  `source_url` text,
  `source_file_key` varchar(1000),
  `source_file_name` varchar(1000),
  `mime_type` varchar(255),
  `is_current` tinyint NOT NULL DEFAULT 1,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(100),
  `occurred_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_work_memory_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_work_memory_source_uq` UNIQUE (`source_system`, `source_record_id`),
  CONSTRAINT `como_next_work_memory_file_fk` FOREIGN KEY (`project_id`, `work_file_id`) REFERENCES `como_next_work_files` (`project_id`, `id`) ON DELETE RESTRICT,
  INDEX `como_next_work_memory_file_idx` (`work_file_id`, `memory_type`, `occurred_at`)
);

CREATE TABLE `como_next_meetings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `project_id` int NOT NULL,
  `work_file_id` int,
  `project_party_id` int,
  `title` varchar(1000) NOT NULL,
  `objective` text,
  `meeting_type` varchar(80),
  `meeting_format` varchar(80),
  `meeting_status` enum('planned','confirmed','completed','cancelled') NOT NULL DEFAULT 'planned',
  `starts_at` timestamp NULL,
  `ends_at` timestamp NULL,
  `timezone` varchar(80) NOT NULL DEFAULT 'Asia/Dubai',
  `location` varchar(1000),
  `meeting_link` text,
  `outcome_summary` longtext,
  `closed_at` timestamp NULL,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_meetings_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_meeting_project_fk` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_meeting_file_fk` FOREIGN KEY (`project_id`, `work_file_id`) REFERENCES `como_next_work_files` (`project_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_meeting_party_fk` FOREIGN KEY (`project_id`, `project_party_id`) REFERENCES `como_next_project_parties` (`project_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_meeting_source_uq` UNIQUE (`source_system`, `source_record_id`),
  INDEX `como_next_meeting_project_time_idx` (`project_id`, `starts_at`),
  INDEX `como_next_meeting_file_time_idx` (`work_file_id`, `starts_at`)
);

CREATE TABLE `como_next_meeting_participants` (
  `id` int AUTO_INCREMENT NOT NULL,
  `meeting_id` int NOT NULL,
  `display_name` varchar(255) NOT NULL,
  `email` varchar(320),
  `organization_name` varchar(500),
  `participant_role` varchar(255),
  `attendance` varchar(80),
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_meeting_participants_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_meeting_participant_meeting_fk` FOREIGN KEY (`meeting_id`) REFERENCES `como_next_meetings` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_meeting_participant_source_uq` UNIQUE (`source_system`, `source_record_id`),
  INDEX `como_next_meeting_participant_meeting_idx` (`meeting_id`)
);

CREATE TABLE `como_next_meeting_agenda_items` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `meeting_id` int NOT NULL,
  `item_kind` varchar(80),
  `category` varchar(255),
  `prompt_ar` text,
  `prompt_en` text,
  `response` longtext,
  `is_checked` tinyint NOT NULL DEFAULT 0,
  `is_required` tinyint NOT NULL DEFAULT 0,
  `sort_order` int NOT NULL DEFAULT 0,
  `briefing_note` text,
  `desired_outcome` text,
  `audience` varchar(80),
  `priority` varchar(80),
  `source_evidence` longtext,
  `source_system` varchar(64) NOT NULL DEFAULT 'como_next',
  `source_record_id` varchar(128),
  `import_batch_id` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `como_next_meeting_agenda_items_id_pk` PRIMARY KEY (`id`),
  CONSTRAINT `como_next_meeting_agenda_meeting_fk` FOREIGN KEY (`meeting_id`) REFERENCES `como_next_meetings` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_meeting_agenda_source_uq` UNIQUE (`source_system`, `source_record_id`),
  INDEX `como_next_meeting_agenda_order_idx` (`meeting_id`, `sort_order`)
);
