-- COMO Next read-only email inbox
-- Additive only. This migration creates an internal review inbox; it does not
-- send, reply, forward, mark messages as read, or schedule mailbox polling.

CREATE TABLE IF NOT EXISTS `como_next_email_messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `mailbox_key` varchar(64) NOT NULL,
  `folder_name` varchar(255) NOT NULL DEFAULT 'INBOX',
  `uid_validity` varchar(64) NOT NULL,
  `imap_uid` bigint NOT NULL,
  `message_id` varchar(1000) NULL,
  `message_id_sha256` varchar(64) NOT NULL,
  `from_email` varchar(320) NOT NULL,
  `from_name` varchar(500) NULL,
  `to_text` text NULL,
  `cc_text` text NULL,
  `subject` varchar(1000) NOT NULL,
  `body_text` longtext NOT NULL,
  `body_sha256` varchar(64) NOT NULL,
  `received_at` timestamp NOT NULL,
  `server_seen` tinyint NOT NULL DEFAULT 0,
  `attachment_count` int NOT NULL DEFAULT 0,
  `inbox_status` enum('unmatched','suggested','linked','dismissed') NOT NULL DEFAULT 'unmatched',
  `importance` enum('unreviewed','normal','important','urgent') NOT NULL DEFAULT 'unreviewed',
  `suggested_project_id` int NULL,
  `suggested_work_file_id` int NULL,
  `suggested_project_party_id` int NULL,
  `suggestion_reason` text NULL,
  `linked_project_id` int NULL,
  `linked_work_file_id` int NULL,
  `linked_project_party_id` int NULL,
  `communication_id` bigint NULL,
  `reply_draft_communication_id` bigint NULL,
  `imported_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `linked_at` timestamp NULL,
  `dismissed_at` timestamp NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `como_next_email_mailbox_uid_uq` (`mailbox_key`,`folder_name`,`uid_validity`,`imap_uid`),
  UNIQUE KEY `como_next_email_mailbox_message_uq` (`mailbox_key`,`message_id_sha256`),
  KEY `como_next_email_user_status_idx` (`user_id`,`inbox_status`,`received_at`),
  KEY `como_next_email_suggestion_idx` (`suggested_project_id`,`suggested_work_file_id`),
  KEY `como_next_email_link_idx` (`linked_project_id`,`linked_work_file_id`,`received_at`),
  CONSTRAINT `como_next_email_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_suggested_project_fk` FOREIGN KEY (`suggested_project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_suggested_file_fk` FOREIGN KEY (`suggested_project_id`,`suggested_work_file_id`) REFERENCES `como_next_work_files` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_suggested_party_fk` FOREIGN KEY (`suggested_project_id`,`suggested_project_party_id`) REFERENCES `como_next_project_parties` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_linked_project_fk` FOREIGN KEY (`linked_project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_linked_file_fk` FOREIGN KEY (`linked_project_id`,`linked_work_file_id`) REFERENCES `como_next_work_files` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_linked_party_fk` FOREIGN KEY (`linked_project_id`,`linked_project_party_id`) REFERENCES `como_next_project_parties` (`project_id`,`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_communication_fk` FOREIGN KEY (`communication_id`) REFERENCES `como_next_communications` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_email_reply_draft_fk` FOREIGN KEY (`reply_draft_communication_id`) REFERENCES `como_next_communications` (`id`) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `como_next_email_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email_message_id` bigint NOT NULL,
  `ordinal` int NOT NULL,
  `file_name` varchar(1000) NOT NULL,
  `mime_type` varchar(255) NOT NULL,
  `byte_size` bigint NOT NULL DEFAULT 0,
  `content_id` varchar(500) NULL,
  `disposition` varchar(80) NULL,
  `storage_status` enum('metadata_only','stored','failed') NOT NULL DEFAULT 'metadata_only',
  `sha256` varchar(64) NULL,
  `document_id` bigint NULL,
  `storage_error` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `como_next_email_attachment_order_uq` (`email_message_id`,`ordinal`),
  KEY `como_next_email_attachment_document_idx` (`document_id`),
  CONSTRAINT `como_next_email_attachment_message_fk` FOREIGN KEY (`email_message_id`) REFERENCES `como_next_email_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `como_next_email_attachment_document_fk` FOREIGN KEY (`document_id`) REFERENCES `como_next_documents` (`id`) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS `como_next_email_analyses` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email_message_id` bigint NOT NULL,
  `request_key` varchar(128) NOT NULL,
  `analysis_status` enum('draft','superseded') NOT NULL DEFAULT 'draft',
  `summary_ar` longtext NOT NULL,
  `importance` enum('normal','important','urgent') NOT NULL DEFAULT 'normal',
  `why_important` text NULL,
  `suggested_next_step` text NULL,
  `reply_draft_text` longtext NULL,
  `evidence_json` longtext NOT NULL,
  `model_id` varchar(120) NOT NULL,
  `requested_by_user_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `como_next_email_analysis_request_uq` (`request_key`),
  KEY `como_next_email_analysis_message_idx` (`email_message_id`,`analysis_status`,`created_at`),
  CONSTRAINT `como_next_email_analysis_message_fk` FOREIGN KEY (`email_message_id`) REFERENCES `como_next_email_messages` (`id`) ON DELETE CASCADE,
  CONSTRAINT `como_next_email_analysis_user_fk` FOREIGN KEY (`requested_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
);
