-- COMO Next: confirmed-Sent email follow-up ledger.
-- Additive only: creates a new ledger and indexes only. It does not alter,
-- backfill, delete, send, or otherwise mutate existing email/communication data.

CREATE TABLE IF NOT EXISTS `como_next_email_followups` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `idempotency_key` varchar(64) NOT NULL,
  `user_id` int NOT NULL,
  `work_file_id` int NOT NULL,
  `sent_message_id` varchar(1000) NOT NULL,
  `sent_message_ref` varchar(500) NOT NULL,
  `sent_at` timestamp NOT NULL,
  `to_text` text NOT NULL,
  `cc_text` text NULL,
  `subject` varchar(1000) NOT NULL,
  `owner_directive_ref` varchar(500) NOT NULL,
  `owner_directive_explicitly_approved` tinyint NOT NULL DEFAULT 0,
  `system_draft_key` varchar(255) NOT NULL,
  `sent_correlation_json` longtext NOT NULL,
  `expected_resolution_kinds` longtext NOT NULL,
  `follow_up_at` timestamp NOT NULL,
  `status` enum('scheduled','drafting','draft_ready','owner_review','cancelled') NOT NULL DEFAULT 'scheduled',
  `draft_claim_token` varchar(64) NULL,
  `draft_claimed_at` timestamp NULL,
  `mailbox_draft_ref` varchar(500) NULL,
  `owner_review_reason` text NULL,
  `last_error` text NULL,
  `resolution_kind` enum('reply','analysis','deliverable','invoice_paid','invoice_approved') NULL,
  `resolution_occurred_at` timestamp NULL,
  `resolution_explicitly_adequate` tinyint NULL,
  `resolution_evidence_ref` varchar(1000) NULL,
  `cancelled_at` timestamp NULL,
  `cancellation_reason` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `como_next_followup_idempotency_uq` UNIQUE (`idempotency_key`),
  CONSTRAINT `como_next_followup_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_next_followup_work_file_fk` FOREIGN KEY (`work_file_id`) REFERENCES `como_next_work_files` (`id`) ON DELETE RESTRICT,
  INDEX `como_next_followup_active_due_idx` (`status`, `follow_up_at`),
  INDEX `como_next_followup_file_sent_idx` (`work_file_id`, `sent_message_ref`),
  INDEX `como_next_followup_user_status_idx` (`user_id`, `status`, `updated_at`)
);
