-- Reviewed and applied by the parent through the official database process on 2026-10-10.
-- Durable Private Email Draft claim ledger. No SMTP, secrets, permissions, or mailbox flags are changed.
CREATE TABLE IF NOT EXISTS `como_mailbox_draft_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `mailbox_key` varchar(64) NOT NULL,
  `draft_key` varchar(255) NOT NULL,
  `user_id` int NULL,
  `project_id` int NULL,
  `work_file_id` int NULL,
  `communication_id` bigint NULL,
  `message_id` varchar(320) NOT NULL,
  `subject_sha256` varchar(64) NOT NULL,
  `body_sha256` varchar(64) NOT NULL,
  `to_envelope_sha256` varchar(64) NOT NULL,
  `cc_envelope_sha256` varchar(64) NOT NULL,
  `state` enum('preappend_claimed','append_started','draft_saved','sent_confirmed','human_review') NOT NULL DEFAULT 'preappend_claimed',
  `claim_token` varchar(64) NULL,
  `claim_expires_at` timestamp NULL,
  `append_started_at` timestamp NULL,
  `draft_folder` varchar(255) NULL,
  `draft_uid` bigint NULL,
  `sent_folder` varchar(255) NULL,
  `sent_uid` bigint NULL,
  `review_reason` varchar(255) NULL,
  `confirmed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `como_mailbox_draft_ledger_key_uq` UNIQUE (`mailbox_key`, `draft_key`),
  CONSTRAINT `como_mailbox_draft_ledger_message_uq` UNIQUE (`mailbox_key`, `message_id`),
  CONSTRAINT `como_mailbox_draft_ledger_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_mailbox_draft_ledger_project_fk` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `como_mailbox_draft_ledger_file_fk` FOREIGN KEY (`project_id`, `work_file_id`) REFERENCES `como_next_work_files` (`project_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `como_mailbox_draft_ledger_communication_fk` FOREIGN KEY (`communication_id`) REFERENCES `como_next_communications` (`id`) ON DELETE RESTRICT,
  INDEX `como_mailbox_draft_ledger_claim_idx` (`state`, `claim_expires_at`),
  INDEX `como_mailbox_draft_ledger_communication_idx` (`communication_id`)
);
