import { useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { default as ArrowRight } from "lucide-react/dist/esm/icons/arrow-right.js";
import { default as ClipboardCheck } from "lucide-react/dist/esm/icons/clipboard-check.js";
import { default as Plus } from "lucide-react/dist/esm/icons/plus.js";
import { default as ShieldCheck } from "lucide-react/dist/esm/icons/shield-check.js";

const statusLabels: Record<string, string> = { not_started: "لم يبدأ", submitted: "مقدم للمراجعة", accepted: "مقبول", returned: "معاد للمراجعة", overdue: "متأخر" };
const statusClass: Record<string, string> = { not_started: "bg-slate-100 text-slate-700", submitted: "bg-blue-100 text-blue-800", accepted: "bg-emerald-100 text-emerald-800", returned: "bg-amber-100 text-amber-900", overdue: "bg-rose-100 text-rose-800" };

export default function ContractDeliverablesPage() {
  const [, navigate] = useLocation();
  const [projectId, setProjectId] = useState<number | null>(null);
  const [contractId, setContractId] = useState<number | null>(null);
  const [isAdding, setIsAdding] = useState(false);
  const [title, setTitle] = useState("");
  const [criteria, setCriteria] = useState("");
  const [dueDate, setDueDate] = useState("");
  const utils = trpc.useUtils();
  const { data: projects = [] } = trpc.projects.list.useQuery();
  const { data: contracts = [] } = trpc.consultantProcurement.listContracts.useQuery({ projectId: projectId ?? 0 }, { enabled: projectId !== null });
  const { data: deliverables = [] } = trpc.consultantProcurement.listDeliverables.useQuery({ projectId: projectId ?? 0, contractId: contractId ?? 0 }, { enabled: projectId !== null && contractId !== null });
  const addMutation = trpc.consultantProcurement.addDeliverable.useMutation({ onSuccess: () => { setTitle(""); setCriteria(""); setDueDate(""); setIsAdding(false); if (projectId && contractId) utils.consultantProcurement.listDeliverables.invalidate({ projectId, contractId }); } });
  const statusMutation = trpc.consultantProcurement.updateDeliverableStatus.useMutation({ onSuccess: () => { if (projectId && contractId) utils.consultantProcurement.listDeliverables.invalidate({ projectId, contractId }); } });

  return <div className="min-h-screen w-full max-w-full overflow-x-hidden bg-background" dir="rtl">
    <header className="sticky top-0 z-40 border-b border-border bg-card/90 backdrop-blur"><div className="mx-auto flex h-14 max-w-6xl items-center gap-3 px-4 sm:px-6"><Button variant="ghost" size="sm" onClick={() => navigate("/consultant-appointment-pack")} className="gap-1.5"><ArrowRight className="h-4 w-4" /> العودة إلى حزمة التكليف</Button><span className="h-5 w-px bg-border" /><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-emerald-700" /><p className="text-sm font-extrabold text-foreground">سجل تسليمات العقد</p></div></div></header>
    <main className="mx-auto w-full max-w-6xl px-4 py-7 sm:px-6"><section className="rounded-3xl border border-emerald-200 bg-gradient-to-l from-emerald-50 via-white to-cyan-50 p-6"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-xl"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-3 py-1 text-xs font-bold text-emerald-800"><ShieldCheck className="h-3.5 w-3.5" /> سجل مستقل لا يعدل العقد</div><h1 className="mt-3 text-2xl font-extrabold text-foreground">تسليمات الاستشاري بعد التعيين</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">اختر عقدًا قائمًا ثم سجل مخرجاته ومعايير قبولها. يبقى العقد نفسه ومرفقاته وشروطه كما هي.</p></div><div className="grid w-full gap-3 sm:grid-cols-2 md:w-[420px]"><select value={projectId ?? ""} onChange={(e) => { setProjectId(e.target.value ? Number(e.target.value) : null); setContractId(null); }} className="h-11 rounded-xl border border-emerald-300 bg-white px-3 text-sm font-semibold"><option value="">— اختر مشروعًا —</option>{projects.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={contractId ?? ""} disabled={!projectId} onChange={(e) => setContractId(e.target.value ? Number(e.target.value) : null)} className="h-11 rounded-xl border border-emerald-300 bg-white px-3 text-sm font-semibold"><option value="">— اختر عقدًا —</option>{contracts.map((c: any) => <option key={c.id} value={c.id}>{c.title}</option>)}</select></div></div></section>
      {projectId && contracts.length === 0 && <p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">لا يوجد عقد لهذا المشروع بعد. يظهر السجل بعد تسجيل عقد قائم فقط.</p>}
      {projectId && contractId && <section className="mt-5 rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-extrabold text-foreground">التسليمات المسجلة</h2><p className="mt-1 text-xs text-muted-foreground">كل حالة تخص التسليم فقط ولا تعدل حالة العقد.</p></div><Button onClick={() => setIsAdding((value) => !value)} className="gap-1.5 bg-emerald-700 hover:bg-emerald-800"><Plus className="h-4 w-4" /> إضافة تسليم</Button></div>{isAdding && <div className="mt-5 grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50/50 p-4 md:grid-cols-2"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="اسم التسليم المطلوب" className="h-10 rounded-lg border border-emerald-300 bg-white px-3 text-sm" /><input value={dueDate} onChange={(e) => setDueDate(e.target.value)} placeholder="تاريخ الاستحقاق (اختياري)" className="h-10 rounded-lg border border-emerald-300 bg-white px-3 text-sm" /><textarea value={criteria} onChange={(e) => setCriteria(e.target.value)} placeholder="معيار القبول أو المطلوب مراجعته" className="min-h-20 rounded-lg border border-emerald-300 bg-white p-3 text-sm md:col-span-2" /><div className="md:col-span-2"><Button disabled={title.trim().length < 2 || addMutation.isPending} onClick={() => addMutation.mutate({ projectId, contractId, title, acceptanceCriteria: criteria || undefined, dueDate: dueDate || undefined })} className="bg-emerald-700 hover:bg-emerald-800">حفظ التسليم في السجل</Button></div></div>}{deliverables.length === 0 ? <p className="mt-6 rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">لا توجد تسليمات مسجلة لهذا العقد بعد.</p> : <div className="mt-5 space-y-3">{deliverables.map((item: any) => <article key={item.id} className="flex flex-col gap-3 rounded-xl border border-border p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-bold text-foreground">{item.title}</p>{item.acceptanceCriteria && <p className="mt-1 text-xs text-muted-foreground">معيار القبول: {item.acceptanceCriteria}</p>}{item.dueDate && <p className="mt-1 text-xs text-muted-foreground">الاستحقاق: {item.dueDate}</p>}</div><select value={item.status} disabled={statusMutation.isPending} onChange={(e) => statusMutation.mutate({ id: item.id, status: e.target.value as any })} className={`h-9 rounded-lg border-0 px-3 text-xs font-bold ${statusClass[item.status]}`}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></article>)}</div>}</section>}
    </main>
  </div>;
}
